Feature/ulid
XOOPS/xmf pull request #100
Opened 2023-05-19 10:11 UTC by mambax7

2023-05-20 16:16 UTC, geekwright requested changes
This is neat!

Can you add a couple of tests?
- generate 2 ULIDs and compare to assert they are unequal
- generate 2 ULIDs and sort to verify they collate properly

Looks good!

2023-05-20 18:17 UTC, mambax7 commented
OK, done!

2023-10-02 03:34 UTC, mambax7 commented
Richard, did you get a chance to look into it?

2023-10-02 22:05 UTC, geekwright requested changes

2023-10-02 22:05 UTC, geekwright commented on src/Ulid.php
> +    private static $lastTime = 0;
This change adding the static needs to be reverted. This should be stateless.

The testing would be generating one ULID, followed by a usleep() then generating another ULID  to compare for proper coalation. Best  guess would be usleep(50000)?

2023-10-03 02:29 UTC, mambax7 commented
Please see the latest changes

2023-10-03 02:33 UTC, mambax7 commented
FYI - here the tests fail on PhpUnit 7.1, and 7.4, but on my PHPUnit 9.6.13 they passed

2023-10-31 17:44 UTC, ggoffy approved these changes

2023-10-31 17:45 UTC, ggoffy approved these changes

2023-10-31 17:45 UTC, ggoffy approved these changes

2023-10-31 17:46 UTC, ggoffy approved these changes

2023-10-31 17:47 UTC, ggoffy approved these changes

2023-10-31 17:47 UTC, ggoffy approved these changes

2023-10-31 17:48 UTC, ggoffy approved these changes

2023-10-31 18:09 UTC, geekwright approved these changes

2023-10-31 19:27 UTC, merged