simplification
XOOPS/xmf pull request #103
Opened 2023-10-30 16:14 UTC by mambax7

2023-10-30 17:19 UTC, ggoffy approved these changes

2023-10-30 17:24 UTC, ggoffy approved these changes

2023-10-30 17:26 UTC, ggoffy approved these changes

2023-10-31 18:39 UTC, geekwright requested changes

2023-10-31 18:39 UTC, geekwright commented on src/ProxyCheck.php
> +    }
Indentation is confusingly wrong

2023-10-31 18:39 UTC, geekwright commented on src/ProxyCheck.php
> +        return $proxyHeader;
I would agree with ggoffy

2023-10-31 21:21 UTC, merged